install/nvgt.nsi
I added a screen in the installer to select whether you'd like to run or edit scripts by default when you click them. I personally prefer to edit scripts.
Theoretically you should be able to do this by selecting a different application to open with, but this removes the other context menu handlers for me, even though they are still present in the registry. I don't know if this is Windows 11 or just a general Windows behavior.
=> Default click behavior for scripts

test/bench/parse_number.nvgt
This PR adds a parse number benchmark.
=> Added parse number benchmark

src/angelscript.cpp
Angel script provides support for math complex functions. Enabling this will help game developers make more scientific games.
=> Included Math Complex Addon

src/sound.cpp, src/sound.h
- **Fixed a bug in the mixer class where an effect would fail to add on occasion but all remaining effects would be added**
- **Finally (and hopefully) fixed all the mixer::set_fx problems.**
=> Fix more mixer::set_fx bugs

release/include/speech.nvgt
So this will allow to set default interrupting, useful in such as configuration
=> Added default_interrupt property in Speech.nvgt to set default interrupting for all the speech

src/angelscript.cpp
support multiline strings for better compatibility with some bgt games
=> add support for multiline strings

doc/src/manual/compiling your project for distribution.md, doc/src/references/builtin/Text-To-Speech/classes/tts_voice/Methods/get_speaking.nvgt, doc/src/references/builtin/Text-To-Speech/classes/tts_voice/Methods/get_voice_count.nvgt, doc/src/references/builtin/Text-To-Speech/classes/tts_voice/Methods/get_volume.nvgt, doc/src/references/builtin/Text-To-Speech/classes/tts_voice/Methods/set_rate.nvgt, doc/src/references/builtin/Text-To-Speech/classes/tts_voice/Methods/set_volume.nvgt
See the commit log, this isn't complete yet and I could use some help understanding how this all works on Linux and Mac OS.
=> adding rough draft of documentation for compiling to executable form for distribution.

doc/src/references/builtin/Audio/Classes/sound/Properties/loaded_filename.md, doc/src/references/builtin/User Interface/Functions/idle_ticks.nvgt
I have added 2 new files according to the docs structure.
=> Added docs for sound::loaded_filename and itle_ticks()

.github/workflows/release.yml, SConstruct, build/build_linux.sh, build/upx_sconscript.py, release/include/form.nvgt
The following methods have been added.
* `bool is_unallowed_char(int control_index, string char, bool search_all=true);` which checks whether the given characters are allowed. It is also possible to make the search_all parameter to true or false to toggle whether the method should search to match full text, or every character. You can also omit the control_index parameter, in which case the method is used internally in the control class.
* `bool set_unallowed_chars(int control_index, string chars, bool use_only_unallowed_chars=false, string char_allow_description="");` which sets the unallowed characters in a given control. Setting the use_only_unallowed_chars parameter to true will restrict to use only characters that have been set into this list. The char_allow_description parameter is …
=> Form new useful methods implementation

release/include/form.nvgt
Hello. I noticed that there is no word deletion function in the audio form, and I tried to add this feature. Before I haven't studied the form.nvgt file too much, I used simple methods when adding this feature. At least it works haha. If there is a problem, I apologize in advance.
Rofl also has a problem with my translation plugin, for some reason it started not being able to translate things properly. That's why I also apologize for the typos.
=> Added word deletion

release/include/form.nvgt, release/include/virtual_dialogs.nvgt
After nvgt has introduced a function to open a link in the default web browser and users have a choice to use run functioin to run external programs as well, the proper Link type is requires, so users have an alternative to the button control. Currently, this control only introduces a link that gives a semantic link control. If the community agrees, we can add default click behavior to it as well.
=> Audio form improvements: added link control type, custom type names, and added support for floating points in sliders

doc/src/references/include/Token Generation (token_gen.nvgt)/!token_gen.md, doc/src/references/include/Token Generation (token_gen.nvgt)/Enums/token_gen_flag.md, doc/src/references/include/Token Generation (token_gen.nvgt)/Functions/!generate_token.nvgt, doc/src/references/include/Token Generation (token_gen.nvgt)/Functions/generate_custom_token.nvgt, release/include/token_gen.nvgt
Function syntax: `string generate_custom_token(int token_length, string characters);`
* `generate_token` function now uses the custom function to generate the characters depending on the mode.
=> Added custom function to token gen

release/include/form.nvgt
This pr fixes 2 bugs after the modification to the slider control.
1. The slider control no longer gives floating slider values even if the step size is an integer.
2. Fixed Navigation bug that didn't moved to the bottom.
=> Slider Bug Fixes

release/include/bgt_compat.nvgt, release/include/settings.nvgt
placed ghost settings object with a functional class
=> Added new settings object

release/include/input_forms.nvgt, test/interact/test_input_forms.nvgt
- **adds input_forms include with functions to quicly retrieve information using an audio form**
- **adds new test_input_forms.nvgt test**
=> input forms

doc/docgen.py, web/src/_includes/footer.liquid, web/src/js/copy.js
* The documentation generator has also been modified to include the NVGT in the 3 backtick code block tags.
=> Added code block copy on website

doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/!audio_form.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_custom_type.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_link_url.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_slider.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/has_custom_type.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/is_disallowed_char.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_disallowed_chars.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_link_url.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_list_properties.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_progress.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_slider.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_text.md, doc/src/references/include/User Data Storage and Retrieval (settings.nvgt)/Classes/settings/Methods/close.md, doc/src/references/include/User Data Storage and Retrieval (settings.nvgt)/Classes/settings/Methods/dump.md, doc/src/references/include/User Data Storage and Retrieval (settings.nvgt)/Classes/settings/Methods/exists.md, doc/src/references/include/User Data Storage and Retrieval (settings.nvgt)/Classes/settings/Methods/has_other_products.md, doc/src/references/include/User Data Storage and Retrieval (settings.nvgt)/Classes/settings/Properties/instant_save.md
Audio form documentation is almost complete
=> New documentation

doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_slider_maximum_value.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_slider_minimum_value.md, release/include/form.nvgt
Auery the minimum and maximum values of a given slider.
`double audio_form::get_slider_minimum_value(int control_index);`
`double audio_form::get_slider_maximum_value(int control_index);`
=> Two new Methods

doc/src/appendix/Contributors.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_line_column.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_line_number.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/get_text.md, doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_enable_search.md, doc/src/references/include/Menu Interface (menu.nvgt)/.MDRoot, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Methods/add_item.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Methods/intro.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Methods/monitor.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Methods/reset.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/automatic_intro.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/click_sound.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/close_sound.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/edge_sound.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/focus_first_item.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/intro_text.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/open_sound.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/pack_file.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/select_sound.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/wrap.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/wrap_delay.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/Properties/wrap_sound.md, doc/src/references/include/Menu Interface (menu.nvgt)/Classes/menu/menu.md, release/include/menu.nvgt
Replaces Heaven Games with my name in the beta testers contribution section
Starts documenting menu.nvgt include.
Documents audio_form::set_enable_search
=> Documentation - set_enable_search, menu.nvgt, minor name change in contributor section

.github/workflows/release.yml, .gitignore, build/build_linux.sh, build/build_macos.sh, doc/src/advanced/Building NVGT For Linux.md, doc/src/advanced/Building NVGT for MacOS.md
Some general improvements to CI and documentation updates:
- CI: We now create virtual environments in GitHub Actions runs.
- Additionally updates the documentation to show how to create virtual environments along with some other small improvements.
=> CI improvements

SConstruct, src/cppmath.cpp, src/pathfinder.cpp
- **Fixed crash in pathfinder due to null-pointer dereference**
=> pathfinder fixes

src/tts.cpp
=> Sorry... forgot to remove unknown_param from script registration.

doc/src/references/include/Number Speaking (number_speaker.nvgt)/classes/number_speaker/properties/pack_file.md, doc/src/references/include/Token Generation (token_gen.nvgt)/Functions/generate_custom_token.nvgt, release/include/number_speaker.nvgt, release/include/rotation.nvgt, release/include/token_gen.nvgt
- Rotation now uses engine's built-in `clamp` method for its clamped calculated methods.
- Token Gen's custom function now accepts an array, to allow random word generation or the same repeated characters. Of course, for backwards compatibility, the string method will still be available as an overloaded function.
- Number speaker is now compatible with the new pack system.
=> Includes Improvements

other/nvgt_crypto.py
This script enables Python users to encrypt and decrypt NVGT data. They can send it back and forth between NVGT and Python, and the encryption and decryption process works both ways.
=> Adds an NVGT encryption and decryption Python script.

src/scriptstuff.cpp
Fixes #175 (just some null pointer checks).
=> Fix Async crash

ASAddon/src/scriptstdstring_utils.cpp
Add optional start and count parameters to allow joining any part of the array.
=> Improve join function
