- release/include/sound_pool.nvgt
Cleans up some redundant code in play_extended. Also makes it so that there is only 1 constructor for soundpool which can optionally take the amount of items it can handle, or otherwise defaults to 100.
> Soundpool - code cleanup

- release/include/dynamic_menu.nvgt
Adds a new function to dynamic_menu (add_multiple_items) that accepts an array of arrays. Each subarray must have at least 1 element. The first element is the text, the second element is the name. For example,
dynamic_menu newmenu;
newmenu.add_multiple_items({{"start game"}, {"end game"}});
Due to the angelscript restrictions, this was the closest I could get to having it be flexible. The original intent was to let regular strings be used for only the text if the developer wanted, and string arrays be used when both text and name need to be specified, but that was not possible.
> dynamic_menu - add_multiple_items

- doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_disallowed_chars.md
- doc/src/references/include/Auditory User Interface (form.nvgt)/Classes/audio_form/Methods/set_enable_go_to_index.md
- doc/src/references/include/Token Generation (token_gen.nvgt)/!token_gen.md
- doc/src/references/include/Token Generation (token_gen.nvgt)/Enums/token_gen_flag {.md
- doc/src/references/include/Token Generation (token_gen.nvgt)/Enums/token_gen_flag.md
- doc/src/references/include/Token Generation (token_gen.nvgt)/Functions/generate_token.nvgt
* Documentation for Token Gen has been updated, including its enum constants.
* Audio Form documentation: `set_enable_go_to_index`, and `set_disallowed_chars`.
> Documentation of audio_form and token_gen

- release/include/form.nvgt
- release/include/speech.nvgt
the change is a bit rudamentary using an if statement to determine the property in question do to me not finding a parse bool function
> made it so that the load and dump functions in the speech.nvgt include also saves if a screenreader should be used or not

- release/include/form.nvgt
This issue is produced only on line 1 where it sets the column minus instead of how it should be.
For example, the issue was, it sets the column to 3 when we set to 4, etc. And so the issue has been resolved.
> Form: Fixed the issue with column when it is used in single line inputs

- release/include/form.nvgt
The following modifications were made:
* Changed key_return pressure so that it could work well in games where this key is also checked, causing conflict.
* Added a check in void add to check if the type of the control is ct_input, otherwise it returns.
* The verification in void check of whether the control was ct_keyboard_area and then launching return was eliminated, this so that the above was verified.
> Form modifications

- web/src/js/copy.js
Previously @braillescreen formatted the code with spaces in the language area, which should not be done, because Cobalt generate `<pre><code class="language-NVGT"></code></pre>`, which is no space. Other formatted areas are left untouched.
> Fixed language detection issue in copy.js

- release/include/form.nvgt
- release/include/settings.nvgt
- test/interact/formtest.nvgt
* The `form::is_disallowed_char` method will now always return true if the character is not allowed. This also automatically checks whether the control index is being used as either blacklist or whitelist, the `use_only_disallowed_characters` parameter.
* Pasting text will now fail if the clipboard contains disallowed characters.
* The settings.nvgt no longer requires bgt_compat.
> Includes improvements

- release/include/bgt_compat.nvgt
I just added some typedefs for some int types that I saw bgt had, which improves backwards compatability. There is no reason to have them in the main part of the engine, at least in my opinion, but they fit here. Also fixed a typo.
> fixed a typo and added in some typedefs

- release/include/form.nvgt
This commit enhances audio form with the ability to disable deletion of text as well as configure clipboard operations'.
1. A new enum `clipboard_flags`: We now have a new enum that offers 3 constants: `clipboard_flag_copy, clipboard_flag_cut_clipboard_paste`. This is internal, and the users don't need to use this.
2. 2 new methods for configuring whether or not you want to allow the users to use backspace or delete keys. a. `bool audio_form::set_enable_delete(int control_index, bool enabled);` b. `bool audio_form::set_delete_disabled_message(int control_index, string mesage);`
3. A new method for setting clipboard_flags: `bool audio_form::set_clipboard_flags(control_index, bool copy, bool cut, bool paste);`
> More Form Enhancements

- release/include/bgt_compat.nvgt
I am converting a full game from bgt to nvgt, and there I found some functionality that has been added to bgt_compat. This pr will fix that. THis enitial commit introudces `hide_game_window`.
> CHanges Related to BGT Compatibility

- .github/CONTRIBUTING.md
- readme.md
- Moved contribution guidelines to .github/CONTRIBUTING.md to make less cluttered.
- Linked the contribution guidelines file from README.
This change also meets the GitHub requirement. This contribution guidelines file will display automatically by GitHub on issues, pull requests, discussions etc when a person creates a new.
> README and Contribution Update

- release/include/menu.nvgt
The recent commit introduced this typo. PLease merge and close. Thanks
> Fixed the Spellings of "sounds_suffix" in menu::reset

- doc/src/references/builtin/Networking/Constants/Event Types.md
This PR aims to improve the current documentation by correcting the event type constant names. Basically, it removes the "_type" portion of the name, so, e.g., "event_type_none" becomes "event_none".
> Update event constant names to reflect actual variable names

- release/include/music.nvgt
Add track.loadd_filename==main_filename in the 192 line statement in the music.nvgt to fix a bug that occurs when both intro and repeat are specified.
> music_manager fix

- src/input.cpp
- test/quick/get_characters.nvgt
- test/quick/get_key_name.nvgt
- test/quick/has_keyboard.nvgt
This PR tries to address get_characters not working on Android by registering the function that start/stop text input. Because SDL 3 allows to disable the behavior of showing the on screen keyboard, we will do by testing a hint. See the test case for that.
This PR registers 3 functons:
1. `bool start_text_input();`
2. `bool stop_text_input()`
3. `bool text_input_active();`.
> An Attempt to Fix get_characters on Android

- release/include/form.nvgt
- test/quick/KEYBOARD_AVAILABLE.nvgt
- test/quick/get_characters.nvgt
This PR fixes some of the issues introduced in recent PRs.
1. Makes the set_read_only method in audio_form class to account for checkboxes.
2. Fixes the KEYBOARD_AVAILABLE test case.
3. Adds an aditional comments in the get_characters in test/quick to explain why we are hiding the keyboard.
> Code maintenance

- src/sound.cpp
- src/sound.h
- src/timestuff.cpp
- src/tts.cpp
Implements the following methods and properties that were part of BGT's calendar:
* bool leap_year
* string month_name
* string weekday_name
* bool valid
* bool add_days(int days)
* bool add_hours(int hours)
* bool add_minutes(int minutes)
* bool add_seconds(int seconds)
* bool add_months(int months)
* bool add_years(int years)
* int64 diff_days(calendar@ other)
* int64 diff_hours(calendar@ other)
* int64 diff_minutes(calendar@ other)
* int64 diff_months(calendar@ other)
* int64 diff_seconds(calendar@ other)
* double diff_years(calendar@ other)
I'm sure that a couple of these implementations could be done better (especially diff_years and add_months) by someone with a mathier brain, but this should at least get BGT code that expects these APIs going.
I also registered these APIs for use …
> Implement all of the missing calendar methods from BGT

- release/include/touch.nvgt
This PR fixes a bug in touch.nvgt that caused compile error. In line 149, the old overload was being used. It has now been replaced with extend method.
> Fixed touch.nvgt

- src/tts.cpp
> Remove forgotten reference to unused TTS argument.

- release/include/basic_character_controller.nvgt
In the previous code, this string returned clockwise rotation. For example, although 359 degrees was closer to North, it returned as North by West Three Quarter North. With this change, the return is provided centered on the center of the directions.
> The translate_yaw_to_direction string returns more accurately.

- release/include/db_props.nvgt
With this change, it is possible to assign indexes in the arrays of DB_List
```database_list items("items");
items.insert_last("hello");
items[0] = "good night";```
> Changed db_props to define set_opindex as property

- .github/workflows/release.yml
This PR introduces a job similar to the publish_release job, but this makes or updates a latest tag, with the most recent code from main, packaged into the respective platform installers.
It creates a latest development version release that's always going to be up to date with main. Think a bleeding edge/nightly build
> Generate a latest development release every time code is merged into main

- src/pack.cpp
I noticed that a game would refuse to run from source if an embedded pack didn't exist, regardless of whether you would be using a pack file in that situation. So I removed the existence check from embed_pack. This makes it easier for a workflow where you would use raw assets to begin with and only build the pack file when you're ready to compile/distribute.
While looking through the code to do this, I also discovered that the find_embedded_packs function merely removed the * prefix when running from source, making an assumption that the disk filename would always be the same as the embedded filename. So I also fixed that to use the disk filename instead.
> Few suggested fixes to embedded pack workflows

- src/nvgt.cpp
- src/nvgt.h
- src/nvgt_angelscript.cpp
- src/scriptstuff.cpp
- src/scriptstuff.h
Implemented a property to get the path of the main script when running from source (MAIN_SCRIPT_PATH). This makes it easy for scripts to force chdir to their own directory for asset location and so on.
Note BGT used to do this automatically, but I opted to add a property so it can be done manually in case a script needs to work from a different directory - presumably that's why cwdir and chdir were added in the first place.
Only works when running from source for now, though it's pretty simple to get the path of a compiled executable with the SCRIPT_EXECUTABLE property.
> Add SCRIPT_PATH property

- src/reactphysics.cpp
- test/quick/rp3d.nvgt
- test/quick/rp3d_2.nvgt
- test/quick/rp3d_basic_sim.nvgt
- test/quick/rp3d_basic_sim_collision_callbacks.nvgt
- test/quick/rp3d_height_field.nvgt
- test/quick/rp3d_logger.nvgt
- test/quick/rp3d_meshes.nvgt
- test/quick/rp3d_multi_object_sim.nvgt
- test/quick/rp3d_raycast.nvgt
- test/quick/rp3d_user_data.nvgt
Expands the current physics wrapper. In particular:
- Fixed world settings not being copiable.
- Fixed add collider not being registered correctly and creating a temporary shape in the background
- Added generic physics shape destroy function for ease of use
- Added support for meshes
- Added a raycasting example
- Added bare bones logging. It is currently impossible to create a custom angelscript physics logger; I think the default one should satisfy the majority of user needs. If there is a demand for it, we can look into exposing a proper interface to do so.
- Added creation of height fields.
- Added support for user data on bodies.
- When adding user data, ensured that we hold a reference to the object and that body destruction releases said reference.
- Added some niceties like being …
> Rp3d features

- dep/_SConscript
- dep/tonar.c
- dep/tonar.h
- jni/Android.mk
- src/nvgt_angelscript.cpp
- src/tonesynth.cpp
- src/tonesynth.h
When I say rough, I mean rough. It works in its most raw form, but still lots to do.
1. Currently uses a system I built for C last September. I'm a beginner when it comes to audio processing, that means lots of AI help, and possibly several rooky errors. It's certainly slower than I'd like. Maybe figure out how good ma_waveform is. Does it have anti-aliasing, for instance?
2. tone_synth::generate_sound() needs an expert on the audio subsystem to review it. I'm using guesswork to assign sound objects, and I can't even find a way to free/release them, so we could be looking at a potential leak.
3. waveform types need rearranging to make them compatible with BGT's waveform types. Currently, 0=sine, 1=square, 2=triangle, 3=saw (in other words, plainest to richest).
4. There's an oversight …
> Rough and early implementation of tone_synth

- dep/tonar.c
- dep/tonar.h
- src/tonesynth.cpp
- src/tonesynth.h
Since tone_synth has now been merged straight into main, I felt a real sense of urgency to try and remove as much flakiness from it as I know how, and that I have found to date.
* Update Tonar to fix some memory initialisation/allocation bugs
* Started work on improving BGT compatibility
* Add cursor facilities (length/position/seek etc)
Also changed the tone_synth class to use g_audio_engine->new_sound() similar to how TTS does it, replacing my previous code that directly called new_global_sound() - I have no idea what should be used when and how, the audio code I'm finding very confusing. Really hope I'm doing everything right in that area.
Still haven't added tempo/note-based manipulation yet, might find time to do that later unless someone beats me to it.
> Several improvements and fixes to tone_synth

- ASAddon/src/print_func.cpp
- src/timestuff.cpp
Resolves #221 (the provided script no longer crashes) and improves print output:
- Spaces are added in between arguments.
- If printing objects, we check if they can be coerced to strings and only print "Registered Object" if we can't be anymore helpful.
> Datetime bugfixes

- src/input.cpp
- src/input.h
- Fixed joystick::set returning info that's out-of-date by pumping events one time. I'm not sure whether this is enough to catch *all* edgecases what with varying hardware, but this seemed to be good enough during testing. Worst case scenario is we mention in documentation that it might be safer to wait a smidge before starting to query for information. This is an SDL/hardware issue, not us.
- Redesigned power level to fatefully follow SDL mappings (for some reason I thought bgt had a power level function).
> Joystick Bugfixes

- src/pack.cpp
Addresses https://github.com/samtupy/nvgt/issues/242
The fix is on line 500 of Pack.cpp:
```
return seekpos(source->tellg() - (std::streampos)start - (std::streampos)in_avail() + off);
```
@samtupy, I believe this is the same line that you and I have had to go back and forth on a few times now, so please let me know if this builds on non-Windows as I'm not currently set up to test that.
What was happening was that instead of seeking to source->tellg() - start - in_avail + off, it was seeking to source->tellg() - (start - in_avail()) + off which of course sends it to a negative offset. The end result was that it was reading garbage data outside the sandbox.
> Section_istream relative seek fix

- dep/tonar.c
- dep/tonar.h
- src/tonesynth.cpp
- src/tonesynth.h
No output would be generated if the synth detected that it would be silent. This is now configurable via the allow_silent_output property.
By default tone_synth is now reset to BGT defaults:
* Initial waveform: Saw
* Allow silence: true
* Start/end fade times: 8, 12.
> Further BGT compatibility in tone_synth

- test/quick/get_key_name.nvgt
- test/quick/legacy_slide_sound.nvgt
- test/quick/legacy_sound_callbacks.nvgt
Changed key_codes type from key_code[]@ to int[]@ in get_key_name.nvgt for compatibility. Renamed slide_sound.nvgt and sound_callbacks.nvgt to legacy_slide_sound.nvgt and legacy_sound_callbacks.nvgt, adding legacy sound plugin pragmas for legacy namespace support.
> Update key handling and rename sound test files

- release/include/bgt_compat.nvgt
Setting slice end to 0 returns an empty string, fixed by explicitly setting the end index.
I recall an issue or PR raised about a bug in slice not so long back, not sure if this has anything to do with it or whether it got resolved.
> Fix bug in string_right

- ASAddon/include/scriptarray.h
- ASAddon/src/scriptarray.cpp
- doc/src/references/builtin/!Containers/Classes/array/Methods/back.nvgt
- doc/src/references/builtin/!Containers/Classes/array/Methods/front.nvgt
Wrote some helpers (front() and back()) that retrieve the first and last elements respectively.
These are functionally the same as array[0] and array[array.length()-1] (or even array[-1] as I learned is now possible while doing this) but thought having specific methods for them would make code more readable and intentions clearer if using an array as a queue or similar structure.
> front() and back() helpers for array
